### ISSUE TITLE
messages.yml not being created on first load

### ISSUE THREAD

**Issue by alexratman** [Sabbertran/gReqBukkit#1]
Plugin Version: gReqBukkit 1.2.1
Also using: gReqBungee 1.2.1

When you first load the plugin it will create config.yml. It does not create a messages.yml. 

When you restart the server the plugin loading loops as it is looking for messages.yml and it does not exist. The only way to fix this is to create an empty messages.yml in its place which it then populates.

**Comment by tobire** [comment]
Fixed in version 1.3.1 (http://www.spigotmc.org/resources/greq.1082/update?update=29473).
Thanks for the info
