### ISSUE TITLE
messages.yml does not parse section signs or ampersands as colours

### ISSUE THREAD

**Issue by alexratman** [Sabbertran/gReqBukkit#2]
Plugin Version: gReqBukkit 1.2.1
Also using: gReqBungee 1.2.1

When the plugin populates messages.yml for the first time it places question marks (?) in the place of section signs (§). Additonally manaually replacing the question marks for either section signs or ampersands (&) does not parse correctly and ends up with errors in chat (please see screenshots below).

![Default messages.yml](https://cloud.githubusercontent.com/assets/873371/6525722/0490b94c-c401-11e4-86b4-1e2fe65e7e86.png)
Default messages.yml

![When changed for section signs and ampersands](https://cloud.githubusercontent.com/assets/873371/6525716/ee63ecac-c400-11e4-80e5-714ab636d616.png)
Section signs change to two ??
Ampersands do not parse

**Comment by tobire** [comment]
Fixed in version 1.3.1 (http://www.spigotmc.org/resources/greq.1082/update?update=29473).
Thanks for the info
