### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by ghost** [Sabbertran/gReqBukkit#5]
Just in-case you (Sabbertran) don't know, this is something that is happening in console on the most recent version of Spigot, which as of now is: [ Build 1.9 (Mar 19, 2016 8:32:10 PM) ].

![untitled](https://cloud.githubusercontent.com/assets/16313385/13961660/db5df692-f033-11e5-918c-9b2037fe13b5.png)

**Comment by tobire** [comment]
As stated here https://www.spigotmc.org/threads/greq.28943/page-7#post-1391747 I won't be doing any changes on gReq 1.X because I'm working on gReq 2. 
But you can just use the method mentioned in the discussion thread to get it working

**Comment by ghost** [comment]
Okay, thanks for the reply
